version: '3'

services:
  ghost:
    image: ghost
    restart: always
    ports:
      - "80:2368"
    volumes:
      - /home/docker/vol_ghost_ws:/var/lib/ghost/content
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - url=http://192.168.99.100/
      - mail__transport=SMTP
      - mail__options__service=Mailgun
      - mail__from=admin@arbors.com
      - mail__options__host=smtp.mailgun.org
      - mail__options__port=587
      - mail__options__auth__user=
      - mail__options__auth__pass=

  db:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=ghostdata
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=123
    volumes:
      - /home/docker/vol_ghost_db:/var/lib/mysql


volumes:
  vol_ghost_db:
  vol_ghost_ws: