version: "3"

services:
    drupal:
        image: drupal
        ports:
            - "80:80"
        container_name: drupal
        volumes:
            - "vol_drupal_sites:/var/www/html/sites"
            - "vol_drupal_modules:/var/www/html/modules"
            - "vol_drupal_profiles:/var/www/html/profiles"
            - "vol_drupal_themes:/var/www/html/themes"
        restart: always
        depends_on:
            - postgres

    postgres:
        image: postgres
        restart: always
        container_name: drupal_postgresdb
        environment:
            - POSTGRES_PASSWORD=123
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        volumes:
            - "vol_drupal_postgresdb:/var/lib/postgresql/data"


volumes: 
    vol_drupal_sites:
    vol_drupal_modules:
    vol_drupal_profiles:
    vol_drupal_themes:
    vol_drupal_postgresdb: